name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
        env:
          HD_APP_ID: ${{secrets.APP_ID}}
          HD_API_HASH: ${{secrets.API_HASH}}
          HD_TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
          HD_AUTH_USERS: ${{secrets.AUTH_USERS}}
          HD_OWNER_ID: ${{secrets.OWNER_ID}}
          HD_Bot_username: ${{secrets.Bot_username}}
          HD_Mega_email: ${{secrets.Mega_email}} 
          HD_Mega_password: ${{secrets.Mega_password}}
          HD_REDIS_PASS: ${{secrets.REDIS_PASS}}
          HD_REDIS_URI: ${{secrets.REDIS_URI}}
          HD_WEBHOOK: ${{secrets.WEBHOOK}}
